### ISSUE TITLE
Key Features

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scipy.org-new#7]
We need to replace
```
      keyfeatures:
        features:
        - title: Powerful N-dimensional arrays
          text:  Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.
        - title: Numerical computing tools
          text: NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.
        - title: Interoperable
          text: NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.
        - title: Performant
          text: The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.
        - title: Easy to use
          text: NumPy's high level syntax makes it accessible and productive for programmers from any background or experience level.
        - title: Open source
          text: Distributed under a liberal [BSD license](https://github.com/numpy/numpy/blob/master/LICENSE.txt), NumPy is developed and maintained [publicly on GitHub](https://github.com/numpy/numpy) by a vibrant, responsive, and diverse [community](/community).
      section5: false
```
in `config.yaml`.
